# Generated by Django 4.2.10 on 2024-03-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='files',
            name='tags',
        ),
        migrations.AddField(
            model_name='files',
            name='tags',
            field=models.ManyToManyField(blank=True, to='mainApp.tag'),
        ),
    ]
